name: Build

"on":
  "push":
    "tags":
      - "v*"
    "branches":
      - "*"
  "pull_request":

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GO111MODULE: "on"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1.20.4'

      - name: Prepare environment
        run: |-
          RELEASE_VERSION="${GITHUB_REF##*/}"
          if [[ "${RELEASE_VERSION}" != v* ]]; then RELEASE_VERSION='dev'; fi
          echo "RELEASE_VERSION=\"${RELEASE_VERSION}@${GITHUB_SHA:0:10}\"" | tee -a $GITHUB_ENV
          go mod vendor

      # Test
      - name: Unit Testing
        run: go test -v .

      # MacOS
      - run: GOOS=darwin GOARCH=amd64 VERSION=${RELEASE_VERSION} make release
      - run: GOOS=darwin GOARCH=arm64 VERSION=${RELEASE_VERSION} make release

      - run: ls -l build/mac-auto-xlan-switch-*

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/v')
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/mac-auto-xlan-switch-*.tar.gz,build/mac-auto-xlan-switch-*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
